### ISSUE TITLE
kdeconnect-indicator not running in gaming mode on steamos v3.5.19

### ISSUE THREAD

**Issue by dbecker801** [Firemoon777/deck-notifications#1]
Expected behavior: 

- Install Decky Notifications plugin
- Launch plugin
- Initiate pairing

Actual behavior:

- Install Decky Notifications plugin
- Launch plugin
- Trusted Devices and Recent Notifications are blank and do not respond to pairing request from phone
- Desktop mode works perfectly

**Comment by Firemoon777** [comment]
Hello.

I can't confirm your issue. My setup:
* steam deck running on SteamOS 3.5.19
* DeckyLoader 2.12.0 (stable)
* KDE Connect for Android 1.30.1

What software do you use to pair with steam deck? 

Make sure that you're connecting to expected device: desktop's KDE Connect won't work in game mode. Moreover, there is no communication between desktop (official) KDE Connect and my plugin. Plugin appears as separate device.

P.S. Can you check logs in `~/homebrew/Decky-Notifications/log/`.

**Comment by dbecker801** [comment]
My setup is exactly the same as yours - SteamOS, DeckyLoader and KDE Connect for Android are exact version matches.

It took several tries but eventually I got the notification to pop up in Gaming Mode after unpairing my phone from the desktop mode connector (I would hear the sound but nothing would pop up). So I'm OK now. Thanks.
